name: Build and Deploy API Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-web5-sdk-kotlin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projects: [
          web5-sdk-kotlin
        ]
    steps:
      - uses: actions/checkout@v3
      # https://cashapp.github.io/hermit/usage/ci/
      - name: Init Hermit
        uses: cashapp/activate-hermit@v1
      - name: Download Dokka CLI and Build HTML APIDocs
        run: |
          wget -O dokka-cli.jar https://repo1.maven.org/maven2/org/jetbrains/dokka/dokka-cli/1.9.20/dokka-cli-1.9.20.jar
          wget -O dokka-base.jar https://repo1.maven.org/maven2/org/jetbrains/dokka/dokka-base/1.9.20/dokka-base-1.9.20.jar
          wget -O analysis-kotlin-descriptors.jar https://repo1.maven.org/maven2/org/jetbrains/dokka/analysis-kotlin-descriptors/1.9.20/analysis-kotlin-descriptors-1.9.20.jar
          wget -O kotlinx-html-jvm.jar https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-html-jvm/0.8.0/kotlinx-html-jvm-0.8.0.jar
          wget -O freemarker.jar https://repo1.maven.org/maven2/org/freemarker/freemarker/2.3.31/freemarker-2.3.31.jar
          java -jar ./dokka-cli.jar dokka-configuration.json
        working-directory: .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: target/apidocs

  deploy-examples:
    runs-on: ubuntu-latest
    needs: [ build-web5-sdk-kotlin ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_dir: ./public
          full_commit_message: Publish documentation to GitHub pages