name: Release and Publish to Maven Central
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish. For example "1.0.0 or 1.0.0-SNAPSHOT"'
        required: true
        default: '0.0.0'
      developmentVersion:
        description: 'Next development version. For example "1.1.0". The system will append "-SNAPSHOT" to the end of this input to reflect the next development version.'
        required: true
        default: "0.0.0"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # https://cashapp.github.io/hermit/usage/ci/
      - name: Init Hermit
        uses: cashapp/activate-hermit@v1

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Adapted from: https://gist.github.com/sualeh/ae78dc16123899d7942bc38baba5203c
      - name: Install gpg secret key
        run: |
          # Install gpg secret key
          cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | gpg --batch --import
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format LONG

      # This will set versions, git tag, and publish to TBD Artifactory. Does not release to Maven Central.
      - name: Staging - Prepare and Publish Release to TBD Artifactory
        run: |
            mvn \
              release:prepare \
              release:stage \
              --batch-mode \
              --settings .maven_settings.xml \
              -DreleaseVersion=${{ github.event.inputs.version }} \
              -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }} \
              -Dgpg.passphrase=${{ secrets.GPG_SECRET_PASSPHRASE }} \
              -DstagingRepository=https://blockxyz.jfrog.io/artifactory/tbd-oss-releases-maven2
        env:
            ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
            ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        # skips snapshot releases
        if: contains(github.event.inputs.version, 'SNAPSHOT') == false
        with:
          tag_name: v${{ github.event.inputs.version }}
          draft: false
          prerelease: true
          generate_release_notes: true
